<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('MyShop'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/app-logo.ico'))
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>


        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/angular.min.js')
        ;
        ?>

    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" style="padding-bottom: 10px;padding-top: 10px;" href="<?php echo $this->url('home') ?>"><img src="<?php echo $this->basePath('img/app-logo.png') ?>" alt="Zend Framework 2"/>&nbsp;<?php echo $this->translate('Admin') ?></a>
                </div>
                <div class="collapse navbar-collapse">
                    <a href="<?php echo $this->url('customer') ?>" class="btn btn-warning navbar-btn">Customers</a>
                    <a href="<?php echo $this->url('product') ?>"class="btn btn-danger navbar-btn">Products</a>
                    <a href="<?php echo $this->url('sale') ?>"class="btn btn-info navbar-btn">Sales</a>
                    <a href="<?php echo $this->url('supplier') ?>"class="btn btn-success navbar-btn">Suppliers</a>
                    <ul class="nav navbar-nav navbar-right collapse navbar-collapse">
                        <li><a href="#">Application</a></li>
                        <?php if ($this->identity()): ?>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php if ($this->identity()) {
                            echo($this->identity()->getUsername());
                        } ?> <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">My profile</a></li>
                                    <li><a href="<?php echo $this->url('user', array('action' => 'connected')) ?>">Online users</a></li>
                                    <li role="separator" class="divider"></li>
                                    <li><a href="<?php echo $this->url('auth', array('action' => 'logout')) ?>">Logout</a></li>

                                </ul>
                            </li>
                        <?php else: ?>
                            <li><a class="navbar-link" href="<?php echo $this->url('auth', array('action' => 'login')) ?>"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Login</a></li>
<?php endif; ?>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
<?php echo $this->content; ?>
            <hr>
            <footer>
                <p></p>
            </footer>
        </div> <!-- /container -->
    </body>
</html>
