<h1>New product</h1>
<?php
$form->setAttribute('action', $this->url('product', array('action' => 'edit', 'id' => $id)));
$form->prepare();
// overrides default error decorator for this form
$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger" role="alert" style="margin-top:1em">')
        ->setMessageSeparatorString('<br />')
        ->setMessageCloseString('</div>');
echo $this->form()->openTag($form);
echo $this->formElement($form->get('csrf'));
?>

<div class="form-group">
    <?php echo $this->formLabel($form->get('product')->get('label')); ?>
    <?php echo $this->formElement($form->get('product')->get('label')); ?>
    <?php echo $this->formElementErrors($form->get('product')->get('label')); ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('product')->get('price')); ?>
    <?php echo $this->formElement($form->get('product')->get('price')); ?>
    <?php echo $this->formElementErrors($form->get('product')->get('price')); ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('product')->get('supplier')); ?>
    <?php echo $this->formElement($form->get('product')->get('supplier')); ?>
    <?php echo $this->formElementErrors($form->get('product')->get('supplier')); ?>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
