<a class="btn btn-danger" href="<?php echo $this->url('product', array('action' => 'add')); ?>">New product</a>
<br /><br />
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
<table id="dtable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Supplier</th>
            <th>Label</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($products as $sale) : ?>
            <tr>
                <td><?php echo $this->escapeHtml($sale->getID()); ?></td>
                <td><?php echo $this->escapeHtml($sale->getSupplier()->getLabel()); ?></td>
                <td><?php echo $this->escapeHtml($sale->getLabel()); ?></td>
                <td>
                    <a class="btn btn-success btn-xs" href="<?php echo $this->url('product', array('action' => 'edit', 'id' => $sale->getID())); ?>">Edit</a>
                    <a class="btn btn-danger btn-xs" href="<?php echo $this->url('product', array('action' => 'delete', 'id' => $sale->getID())); ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php
 echo $this->paginationControl(
     // the paginator object
     $products,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'product'
     )
 );