<a class="btn btn-default" href="<?php echo $this->url('product', array('action' => 'add')); ?>">New product</a>
<br /><br />
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<table id="dtable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th></th>
            <th>ID</th>
            <th>Supplier</th>
            <th>Label</th>
            <th>Price</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($products as $product) : ?>
            <tr>
                <td style="text-align: center">
                    <a href="<?php echo $this->url('product', array('action' => 'delete', 'id' => $product->getId())); ?>" type="button" class="btn btn-danger btn-sm" aria-label="Justify"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                </td>
                <td>
                    <a href="<?php echo $this->url('product', array('action' => 'edit', 'id' => $product->getID())); ?>"><?php echo $this->escapeHtml($product->getID()); ?></a>
                </td>
                <td><?php echo $this->escapeHtml($product->getSupplier()->getLabel()); ?></td>
                <td><?php echo $this->escapeHtml($product->getLabel()); ?></td>
                <td><?php echo $this->escapeHtml($product->getPrice()); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php
echo $this->paginationControl(
        // the paginator object
        $products,
        // the scrolling style
        'sliding',
        // the partial to use to render the control
        'partial/paginator.phtml',
        // the route to link to when a user clicks a control link
        array(
    'route' => 'product'
        )
);
