<?php

/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules'                 => array(
        'Application',
        'Admin',
        'ZendDeveloperTools',
        'DoctrineModule',
        'DoctrineORMModule',
        'Tests',
        'BjyProfiler',
    //'ZfcTwig'
    ),
    'module_listener_options' => array(
        'module_paths'             => array(
            './module',
            './vendor',
        ),
        'config_glob_paths'        => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
        ),
        //'config_cache_enabled'     => false,
        //'module_map_cache_enabled' => true,
        //'cache_dir'                => 'data/cache/',
    ),
);
