<h1>User Edit</h1>
<?php
$form->setAttribute('action', $this->url('user', array('action' => 'edit','id' => $id)));
$form->prepare();
// overrides default error decorator for this form
$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger" role="alert" style="margin-top:1em">')
        ->setMessageSeparatorString('<br />')
        ->setMessageCloseString('</div>');
echo $this->form()->openTag($form);
echo $this->formElement($form->get('csrf'));
?>
<div class="form-group">
    <?php echo $this->formLabel($form->get('username')); ?>
    <?php echo $this->formElement($form->get('username')); ?>
    <?php echo $this->formElementErrors($form->get('username')); ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('email')); ?>
    <?php echo $this->formElement($form->get('email')); ?>
    <?php echo $this->formElementErrors($form->get('email')); ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('role')); ?>
    <?php echo $this->formElement($form->get('role')); ?>
    <?php echo $this->formElementErrors($form->get('role')); ?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('password')); ?>
    <?php echo $this->formElement($form->get('password')); ?>
    <?php echo $this->formElementErrors($form->get('password')); ?>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
