<a class="btn btn-default" href="<?php echo $this->url('user', array('action' => 'add')); ?>">New user</a>
<br /><br />
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
<table id="dtable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($users as $user) : ?>
            <tr>
                <td><a href="<?php echo $this->url('user', array('action' => 'edit', 'id' => $user->id)); ?>"><?php echo $this->escapeHtml($user->id); ?></a></td>
                <td><?php echo $this->escapeHtml($user->username); ?></td>
                <td><?php echo $this->escapeHtml($user->email); ?></td>
                <td><?php echo $this->escapeHtml($user->role); ?></td>

            </tr>
        <?php endforeach; ?>
    </tbody>
</table>