<br /><br />
<div class="panel panel-default">
    <div class="panel-heading" style="font-size:1.2em">This application is a learning case of these technologies : </div>
    <div class="panel-body" style="background:#F4F4F4">
            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath() ?>/img/zf2.png">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath() ?>/img/doctrine2.png">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath() ?>/img/angular.png">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath() ?>/img/jquery.png">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath() ?>/img/bootstrap.png">
                    </a>
                </div>
                <div class="col-xs-6 col-md-3">
                    <a href="#" class="thumbnail">
                        <img src="<?php echo $this->basePath() ?>/img/twig.png">
                    </a>
                </div>
            </div>
    </div>
</div>
<script>
