<h1>Edit customer</h1>
<?php
$form->setAttribute('action', $this->url('customer', array('action' => 'edit', 'id' => $id)));
$form->prepare();
// overrides default error decorator for this form
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger" role="alert" style="margin-top:1em">')
    ->setMessageSeparatorString('<br />')
    ->setMessageCloseString('</div>');
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formLabel($form->get('label')); ?>
    <?php echo $this->formElement($form->get('label')); ?>
    <?php echo $this->formElementErrors($form->get('label'));?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('address')); ?>
    <?php echo $this->formElement($form->get('address')); ?>
    <?php echo $this->formElementErrors($form->get('address'));?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('country')); ?>
    <?php echo $this->formElement($form->get('country')); ?>
    <?php echo $this->formElementErrors($form->get('country'));?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('date')); ?>
    <?php echo $this->formElement($form->get('date')); ?>
    <?php echo $this->formElementErrors($form->get('date'));?>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
