<a class="btn btn-warning" href="<?php echo $this->url('customer', array('action' => 'add')); ?>">New customer</a>
<br /><br />
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
<table id="dtable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Actions</th>
            <th>ID</th>
            <th>Label</th>
            <th>Address</th>
            <th>Date.1ère.Trans</th>
            <th>Country</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($customers as $customer) : ?>
            <tr>
                <td style="text-align: center">
                    <a href="<?php echo $this->url('customer', array('action' => 'delete', 'id' => $customer->getId())); ?>" type="button" class="btn btn-danger btn-sm" aria-label="Justify"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                </td>
                <td><a href="<?php echo $this->url('customer', array('action' => 'edit', 'id' => $customer->getId())); ?>"><?php echo $this->escapeHtml($customer->getID()); ?></a></td>
                <td><?php echo $this->escapeHtml($customer->getLabel()); ?></td>
                <td><?php echo $this->escapeHtml($customer->getAddress()); ?></td>
                <td><?php echo ($customer->getDate()) ? $this->escapeHtml($customer->getDate('l d, F, Y')) : '-'; ?></td>
                <td><?php echo $this->escapeHtml($customer->getCountry()->getLabel()); ?></td>
                <td>
                    <a class="btn btn-primary btn-xs" href="<?php echo $this->url('customer', array('action' => 'sales', 'id' => $customer->getId())); ?>">Sales</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php
 echo $this->paginationControl(
     // the paginator object
     $customers,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'home'
     )
 );