<div ng-app="myapp" ng-controller="CustomerController">
    <a class="btn btn-warning" href="<?php echo $this->url('customer', array('action' => 'add')); ?>">New customer</a>
    <br /><br />
    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success')); ?>
    <?php
    $form->setAttribute('action', $this->url('customer', array('action' => 'index')));
    $form->setAttribute('ng-submit', 'validateForm($event)');
    $form->setAttribute('id', $form->getName());
    $form->prepare();
    foreach($form->getAttributes() as $key => $value){
        $attibs [] = "$key='$value'";
    }
    ?>
    <form <?=implode(' ',$attibs)?>>
    <div class="row">
        <div class="col-md-2">
            <div class="form-group">
                <?php echo $this->formElement($customerFieldset->get('label')); ?>
                <?php echo $this->formElementErrors($customerFieldset->get('label')); ?>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <?php echo $this->formElement($customerFieldset->get('address')); ?>
                <?php echo $this->formElementErrors($customerFieldset->get('address')); ?>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <?php echo $this->formElement($customerFieldset->get('country')); ?>
                <?php echo $this->formElementErrors($customerFieldset->get('country')); ?>
            </div>
        </div>
        <div class="col-md-2">
            <div class="form-group">
                <?php echo $this->formElement($customerFieldset->get('date')); ?>
                <?php echo $this->formElementErrors($customerFieldset->get('date')); ?>
            </div>
        </div>
    </div>
    <?php
    echo $this->formSubmit($form->get('submit'));
    ?>
    </form>
    <hr>
    <table id="dtable" class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>ID</th>
                <th>Label</th>
                <th>Address</th>
                <th>First transaction date</th>
                <th>Country</th>
            </tr>
        </thead>
        <tbody>
            <tr ng-repeat="row in customers">
                <td>{{ row.id}}</td>
                <td>{{ row.label}}</td>
                <td>{{ row.address}}</td>
                <td>{{ row.date}}</td>
                <td>{{ row.country}}</td>
            </tr>
        </tbody>
    </table>
    <div>
        <ul class="pagination">
            <li ng-class="{'disabled' : !pages.first}"><a ng-click="loadpage(pages.first)"><?= $this->escapeHtml('<<') ?></a></li>
            <li ng-class="{'disabled' : !pages.previous}"><a ng-click="loadpage(pages.previous)"><?= $this->escapeHtml('<') ?></a></li>
            <li ng-class="{'active' : page === pages.current}" ng-repeat="page in pages.pagesInRange"><a ng-click="loadpage(page)">{{page}}</a></li>
            <li ng-class="{'disabled' : !pages.next}"><a ng-click="loadpage(pages.next)"><?= $this->escapeHtml('>') ?></a></li>
            <li ng-class="{'disabled' : !pages.last}"><a ng-click="loadpage(pages.last)"><?= $this->escapeHtml('>>') ?></a></li>
        </ul>
    </div>
</div>
<script>
    $(function(){

    })
    var app = angular.module('myapp', []);
    app.config(['$httpProvider', function ($httpProvider) {
            // ajouter ce paramètre aux appels envoyés avec ajax pour pouvoir être détectés par AjaxContext
            $httpProvider.defaults.headers.common["X-Requested-With"] = 'XMLHttpRequest';
        }]);
    app.controller('CustomerController', function ($scope, $http, $compile) {
        $http.get('<?php echo $this->url('customer', array('action' => 'ajax-pages')) ?>', {params: {page: 1}}).success(
                function (response) {
                    $scope.customers = response.customers;
                    $scope.pages = response.pages;
                });
        $scope.loadpage = function (page) {
            $http.get('<?php echo $this->url('customer', array('action' => 'ajax-pages')) ?>', {params: {page: page}}).success(
                    function (response) {
                        $scope.customers = response.customers;
                        $scope.pages = response.pages;
                    });
        }
        $scope.validateForm = function(event){
            console.log($("#searchCustomerForm").serializeArray());
            alert('true');
            event.preventDefault();
        }
    });
</script>