<h2><b><?=$customer->getLabel()?></b> <small>sales' list</small></h2>
<table id="dtable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Actions</th>
            <th>ID</th>
            <th>Date</th>
            <th>Product</th>
            <th>Quantity</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($sales as $sale) : ?>
            <tr>
                <td style="text-align: center">
                    <a href="<?php echo $this->url('sale', array('action' => 'delete', 'id' => $sale->getId())); ?>" type="button" class="btn btn-danger btn-sm" aria-label="Justify"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                </td>
                <td><a href="<?php echo $this->url('sale', array('action' => 'edit', 'id' => $sale->getId())); ?>"><?php echo $this->escapeHtml($sale->getID()); ?></a></td>
                <td><?php echo $this->escapeHtml($sale->getProduct()->getLabel()); ?></td>
                <td><?php echo $this->escapeHtml($sale->getQuantity()); ?></td>
                <td><?php echo ($sale->getDate()) ? $this->escapeHtml($sale->getDate('l d, F, Y')) : '-'; ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

