<h1>New Supplier</h1>
<?php
$form->setAttribute('action', $this->url('supplier', array('action' => 'edit', 'id' => $id)));
$form->prepare();
// overrides default error decorator for this form
$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger" role="alert" style="margin-top:1em">')
    ->setMessageSeparatorString('<br />')
    ->setMessageCloseString('</div>');
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <?php echo $this->formLabel($form->get('label')); ?>
    <?php echo $this->formElement($form->get('label')); ?>
    <?php echo $this->formElementErrors($form->get('label'));?>
</div>
<div class="form-group">
    <?php echo $this->formLabel($form->get('email')); ?>
    <?php echo $this->formElement($form->get('email')); ?>
    <?php echo $this->formElementErrors($form->get('email'));?>
</div>
<?php
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
