<a class="btn btn-default" href="<?php echo $this->url('supplier', array('action' => 'add')); ?>">New supplier</a>
<br /><br />
<?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
<table id="dtable" class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>Actions</th>
            <th>ID</th>
            <th>Label</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($suppliers as $supplier) : ?>
            <tr>
                <td style="text-align: center">
                    <a href="<?php echo $this->url('supplier', array('action' => 'delete', 'id' => $supplier->getId())); ?>" type="button" class="btn btn-danger btn-sm" aria-label="Justify"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                </td>
                <td><a href="<?php echo $this->url('supplier', array('action' => 'edit', 'id' => $supplier->getId())); ?>"><?php echo $this->escapeHtml($supplier->getID()); ?></a></td>
                <td><?php echo $this->escapeHtml($supplier->getLabel()); ?></td>
                <td><?php echo $this->escapeHtml($supplier->getEmail()); ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php
 echo $this->paginationControl(
     // the paginator object
     $suppliers,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     'partial/paginator.phtml',
     // the route to link to when a user clicks a control link
     array(
         'route' => 'supplier'
     )
 );
