<?php
$form->setAttribute('action', $this->url('auth', array('action' => 'login')));
$form->prepare();
// overrides default error decorator for this form
$this->formElementErrors()
        ->setMessageOpenFormat('<div class="alert alert-danger" role="alert" style="margin-top:1em">')
        ->setMessageSeparatorString('<br />')
        ->setMessageCloseString('</div>');
?>
<script>
    $(function () {
        $('#myModal').modal();
    })
</script>
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <?php echo $this->form()->openTag($form);?>
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Application login</h4>
            </div>
            <div class="modal-body">
                <?php
                echo $this->formElement($form->get('csrf'));
                ?>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('login')->get('username')); ?>
                    <?php echo $this->formElement($form->get('login')->get('username')); ?>
                    <?php echo $this->formElementErrors($form->get('login')->get('username')); ?>
                </div>
                <div class="form-group">
                    <?php echo $this->formLabel($form->get('login')->get('password')); ?>
                    <?php echo $this->formElement($form->get('login')->get('password')); ?>
                    <?php echo $this->formElementErrors($form->get('login')->get('password')); ?>
                </div>
            </div>
            <div class="modal-footer">
                <?php echo $this->formSubmit($form->get('submit'));?>
            </div>
            <?php echo $this->form()->closeTag();?>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->